### ISSUE TITLE
Level 4 (Marge) "Ketchup Logic" mission bug

### ISSUE THREAD

**Issue by f00god** [ZenoArrows/The-Simpsons-Hit-and-Run#16] opened 2023-10-14 14:11 UTC
Mission 3 "Ketchup Logic" has a part of the mission where you, with the purchased prison uniform, must go to Cletus car and press Y button. After which you find yourself in an endless mission loading window.

Tried it on two different PC builds. 
Both 0.1 and 0.2 patches. 
Updated my Firmware from 15.0.1  to 16.1.0

No effect :(

**Comment by ZenoArrows** [comment] 2023-10-14 19:16
Reproduced the error on the switch. It's doesn't repro on a Windows build of the same code though, so this might take a bit to fix.

**Comment by masyanolchik** [comment] 2023-10-15 04:09
Idk if it will help to fix this but here is my observation.
This level has sound issues. You can't hear characters at all and there are no engine sounds from cars.
It may appear for one or two voice lines after you sit in any other car except Canyonero.
For example, after I've spawned a car with a payphone and sat in it Marge says one voice line, world starts to dissappear, if you attempt to start any race or mission after that you'll get an endless loading.

**Comment by ZenoArrows** [comment] 2023-10-15 12:33
Interestingly this seems to be any issue only on the release version. On my debug builds this level works fine and I cannot reproduce these issues.

**Comment by ZenoArrows** [comment] 2023-10-15 14:12
It looks like a lot of other issues are connected to this. Solving it should make the game a lot more stable.

**Comment by ZenoArrows** [comment] 2023-10-21 02:30
Should be fixed in version 0.4

**Closed by ZenoArrows** 2023-10-21 02:30 UTC
