### ISSUE TITLE
Icons are too big

### ISSUE THREAD

**Issue by RetroMarioBros** [ZenoArrows/The-Simpsons-Hit-and-Run#15] opened 2023-10-14 08:03 UTC
,First of all, thank you very much, for the PAL version, it works perfectly
Issue 1:
The icons are too big for the Spanish language, and they cut off words
![16972705153453231206852179109721](https://github.com/ZenoArrows/The-Simpsons-Hit-and-Run/assets/6499349/78bf3ad3-d2f0-4756-a9ee-93c57505fbc4)

Issue 2:
exit in the pause menu appears as ??? in the Spanish language

Issue 3 : Pal & ntcs version
In the video player, when playing a video, the video plays perfectly, but the TV image remains underneath...

**Comment by RetroMarioBros** [comment] 2023-10-14 09:26
![16972755079301933356826221545416](https://github.com/ZenoArrows/The-Simpsons-Hit-and-Run/assets/6499349/f8d1796b-dcfd-45d2-8092-4eaed8851831)

![Uploading 16972755617261523358735322390012.jpg…]()

**Comment by RetroMarioBros** [comment] 2023-10-14 09:27
![16972756456284238944322411099143](https://github.com/ZenoArrows/The-Simpsons-Hit-and-Run/assets/6499349/24007965-404c-4a41-b45a-c037542d1712)

**Comment by ZenoArrows** [comment] 2023-10-14 12:28
First issue is a general issue due to the new higher resolution button icons, I forgot to scale them down for the mission accept screen. I noticed the second issue as well with the other languages, not sure why those were not translated.

The last issue is due to widescreen support, but I kind of like the TV remaining underneath, you're watching a movie after all, so it's not a priority for me to fix. (It's not a bug, it's a feature)

**Comment by ZenoArrows** [comment] 2023-10-14 19:21
Fixed in version 0.3

**Closed by ZenoArrows** 2023-10-14 19:21 UTC

**Comment by RetroMarioBros** [comment] 2023-10-14 19:51
Thanks you!! ☺️☺️☺️
